// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package se.kth.md.it.bcm.resources;

// spotless:off
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.Iterator;

import org.eclipse.lyo.oslc4j.core.OSLC4JUtils;
import org.eclipse.lyo.oslc4j.core.exception.OslcCoreApplicationException;
import org.eclipse.lyo.oslc4j.core.annotation.OslcAllowedValue;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDescription;
import org.eclipse.lyo.oslc4j.core.annotation.OslcMemberProperty;
import org.eclipse.lyo.oslc4j.core.annotation.OslcName;
import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespace;
import org.eclipse.lyo.oslc4j.core.annotation.OslcOccurs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRdfCollectionType;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRange;
import org.eclipse.lyo.oslc4j.core.annotation.OslcReadOnly;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRepresentation;
import org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape;
import org.eclipse.lyo.oslc4j.core.annotation.OslcTitle;
import org.eclipse.lyo.oslc4j.core.annotation.OslcValueType;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.Occurs;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.Representation;
import org.eclipse.lyo.oslc4j.core.model.ValueType;
import org.eclipse.lyo.oslc4j.core.model.ResourceShape;
import org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory;

import se.kth.md.it.bcm.resources.BugzDomainConstants;
import se.kth.md.it.bcm.resources.ChangeRequest;
import se.kth.md.it.bcm.resources.BugzDomainConstants;
import se.kth.md.it.bcm.resources.Person;
import se.kth.md.it.bcm.resources.Type;
// Start of user code imports
// End of user code
// spotless:on

// Start of user code preClassCode
// End of user code

// Start of user code classAnnotations
// End of user code
@OslcNamespace(BugzDomainConstants.BUGZILLACHANGEREQUEST_NAMESPACE)
@OslcName(BugzDomainConstants.BUGZILLACHANGEREQUEST_LOCALNAME)
@OslcResourceShape(title = "BugzillaChangeRequest Shape", describes = BugzDomainConstants.BUGZILLACHANGEREQUEST_TYPE)
public class BugzillaChangeRequest
    extends ChangeRequest
    implements IBugzillaChangeRequest
{
    // Start of user code attributeAnnotation:priority
    // End of user code
    private String priority;
    // Start of user code attributeAnnotation:platform
    // End of user code
    private String platform;
    // Start of user code attributeAnnotation:version
    // End of user code
    private String version;
    // Start of user code attributeAnnotation:component
    // End of user code
    private String component;
    // Start of user code attributeAnnotation:product
    // End of user code
    private String product;
    // Start of user code attributeAnnotation:operatingSystem
    // End of user code
    private String operatingSystem;
    
    // Start of user code classAttributes
    // End of user code
    // Start of user code classMethods
    // End of user code
    public BugzillaChangeRequest()
    {
        super();
    
        // Start of user code constructor1
        // End of user code
    }
    
    public BugzillaChangeRequest(final URI about)
    {
        super(about);
    
        // Start of user code constructor2
        // End of user code
    }
    
    public static ResourceShape createResourceShape() throws OslcCoreApplicationException, URISyntaxException {
        return ResourceShapeFactory.createResourceShape(OSLC4JUtils.getServletURI(),
        OslcConstants.PATH_RESOURCE_SHAPES,
        BugzDomainConstants.BUGZILLACHANGEREQUEST_PATH,
        BugzillaChangeRequest.class);
    }
    
    
    public String toString()
    {
        return toString(false);
    }
    
    public String toString(boolean asLocalResource)
    {
        String result = "";
        // Start of user code toString_init
        // End of user code
    
        if (asLocalResource) {
            result = result + "{a Local BugzillaChangeRequest Resource} - update BugzillaChangeRequest.toString() to present resource as desired.";
            // Start of user code toString_bodyForLocalResource
            // End of user code
        }
        else {
            result = String.valueOf(getAbout());
        }
    
        // Start of user code toString_finalize
        // End of user code
    
        return result;
    }
    
    
    // Start of user code getterAnnotation:priority
    // End of user code
    @OslcName("priority")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "priority")
    @OslcDescription("The Bugzilla priority for this change request.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    @OslcTitle("Priority")
    public String getPriority()
    {
        // Start of user code getterInit:priority
        // End of user code
        return priority;
    }

    // Start of user code getterAnnotation:platform
    // End of user code
    @OslcName("platform")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "platform")
    @OslcDescription("The Bugzilla platform for this change request.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    @OslcTitle("Platform")
    public String getPlatform()
    {
        // Start of user code getterInit:platform
        // End of user code
        return platform;
    }

    // Start of user code getterAnnotation:version
    // End of user code
    @OslcName("version")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "version")
    @OslcDescription("The Bugzilla version for this change request.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(true)
    @OslcTitle("Version")
    public String getVersion()
    {
        // Start of user code getterInit:version
        // End of user code
        return version;
    }

    // Start of user code getterAnnotation:component
    // End of user code
    @OslcName("component")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "component")
    @OslcDescription("The Bugzilla product definition for this change request.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    @OslcTitle("Component")
    public String getComponent()
    {
        // Start of user code getterInit:component
        // End of user code
        return component;
    }

    // Start of user code getterAnnotation:product
    // End of user code
    @OslcName("product")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "product")
    @OslcDescription("")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    public String getProduct()
    {
        // Start of user code getterInit:product
        // End of user code
        return product;
    }

    // Start of user code getterAnnotation:operatingSystem
    // End of user code
    @OslcName("operatingSystem")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "operatingSystem")
    @OslcDescription("The Bugzilla operating system for this change request.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    @OslcTitle("Operating System")
    public String getOperatingSystem()
    {
        // Start of user code getterInit:operatingSystem
        // End of user code
        return operatingSystem;
    }

    // Start of user code setterAnnotation:priority
    // End of user code
    public void setPriority(final String priority )
    {
        // Start of user code setterInit:priority
        // End of user code
        this.priority = priority;
        // Start of user code setterFinalize:priority
        // End of user code
    }

    // Start of user code setterAnnotation:platform
    // End of user code
    public void setPlatform(final String platform )
    {
        // Start of user code setterInit:platform
        // End of user code
        this.platform = platform;
        // Start of user code setterFinalize:platform
        // End of user code
    }

    // Start of user code setterAnnotation:version
    // End of user code
    public void setVersion(final String version )
    {
        // Start of user code setterInit:version
        // End of user code
        this.version = version;
        // Start of user code setterFinalize:version
        // End of user code
    }

    // Start of user code setterAnnotation:component
    // End of user code
    public void setComponent(final String component )
    {
        // Start of user code setterInit:component
        // End of user code
        this.component = component;
        // Start of user code setterFinalize:component
        // End of user code
    }

    // Start of user code setterAnnotation:product
    // End of user code
    public void setProduct(final String product )
    {
        // Start of user code setterInit:product
        // End of user code
        this.product = product;
        // Start of user code setterFinalize:product
        // End of user code
    }

    // Start of user code setterAnnotation:operatingSystem
    // End of user code
    public void setOperatingSystem(final String operatingSystem )
    {
        // Start of user code setterInit:operatingSystem
        // End of user code
        this.operatingSystem = operatingSystem;
        // Start of user code setterFinalize:operatingSystem
        // End of user code
    }

}
