// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package se.kth.md.it.bcm.resources;

// spotless:off
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Date;

import org.eclipse.lyo.oslc4j.core.OSLC4JUtils;
import org.eclipse.lyo.oslc4j.core.exception.OslcCoreApplicationException;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDescription;
import org.eclipse.lyo.oslc4j.core.annotation.OslcName;
import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespace;
import org.eclipse.lyo.oslc4j.core.annotation.OslcOccurs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcReadOnly;
import org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape;
import org.eclipse.lyo.oslc4j.core.annotation.OslcTitle;
import org.eclipse.lyo.oslc4j.core.annotation.OslcValueType;

import org.eclipse.lyo.oslc4j.core.model.AbstractResource;
import org.eclipse.lyo.oslc4j.core.model.Occurs;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.Representation;
import org.eclipse.lyo.oslc4j.core.model.ValueType;
import org.eclipse.lyo.oslc4j.core.model.ResourceShape;
import org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory;

import se.kth.md.it.bcm.resources.BugzDomainConstants;
// Start of user code imports
// End of user code
// spotless:on

// Start of user code preClassCode
// End of user code

// Start of user code classAnnotations
// End of user code
@OslcNamespace(BugzDomainConstants.BUGZILLA_NAMSPACE)
@OslcName("comment")
@OslcResourceShape(title = "Bugzilla Comment Shape", describes = BugzDomainConstants.BUGZILLA_NAMSPACE + "comment")
public class BugzillaComment
    extends AbstractResource
{
    // Start of user code attributeAnnotation:commentId
    // End of user code
    private String commentId;
    // Start of user code attributeAnnotation:commentCount
    // End of user code
    private Integer commentCount;
    // Start of user code attributeAnnotation:author
    // End of user code
    private String author;
    // Start of user code attributeAnnotation:authorName
    // End of user code
    private String authorName;
    // Start of user code attributeAnnotation:content
    // End of user code
    private String content;
    // Start of user code attributeAnnotation:created
    // End of user code
    private Date created;
    // Start of user code attributeAnnotation:isPrivate
    // End of user code
    private Boolean isPrivate;
    
    // Start of user code classAttributes
    // End of user code
    // Start of user code classMethods
    // End of user code
    public BugzillaComment()
    {
        super();

        // Start of user code constructor1
        // End of user code
    }
    

    public BugzillaComment(final URI about)
    {
        super(about);

        // Start of user code constructor2
        // End of user code
    }
    
    public static ResourceShape createResourceShape() throws OslcCoreApplicationException, URISyntaxException {
        return ResourceShapeFactory.createResourceShape(OSLC4JUtils.getServletURI(),
        OslcConstants.PATH_RESOURCE_SHAPES,
        BugzDomainConstants.BUGZILLA_NAMSPACE + "comment",
        BugzillaComment.class);
    }
    

    public String toString()
    {
        return toString(false);
    }

    public String toString(boolean asLocalResource)
    {
        String result = "";
        // Start of user code toString_init
        // End of user code

        if (asLocalResource) {
            result = result + "{a Local BugzillaComment Resource} - update BugzillaComment.toString() to present resource as desired.";
            // Start of user code toString_bodyForLocalResource
            // End of user code
        }
        else {
            result = String.valueOf(getAbout());
        }

        // Start of user code toString_finalize
        result = "Comment %s by %s".formatted(getCommentId(), getAuthorName());
        // End of user code

        return result;
    }

    // Start of user code getterAnnotation:commentId
    // End of user code
    @OslcName("commentId")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "commentId")
    @OslcDescription("The Bugzilla comment ID.")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(true)
    @OslcTitle("Comment ID")
    public String getCommentId()
    {
        // Start of user code getterInit:commentId
        // End of user code
        return commentId;
    }

    // Start of user code getterAnnotation:commentCount
    // End of user code
    @OslcName("commentCount")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "commentCount")
    @OslcDescription("The comment count (0 for description, 1+ for actual comments).")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.Integer)
    @OslcReadOnly(true)
    @OslcTitle("Comment Count")
    public Integer getCommentCount()
    {
        // Start of user code getterInit:commentCount
        // End of user code
        return commentCount;
    }

    // Start of user code getterAnnotation:author
    // End of user code
    @OslcName("author")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "author")
    @OslcDescription("The email of the comment author.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(true)
    @OslcTitle("Author")
    public String getAuthor()
    {
        // Start of user code getterInit:author
        // End of user code
        return author;
    }

    // Start of user code getterAnnotation:authorName
    // End of user code
    @OslcName("authorName")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "authorName")
    @OslcDescription("The name of the comment author.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(true)
    @OslcTitle("Author Name")
    public String getAuthorName()
    {
        // Start of user code getterInit:authorName
        // End of user code
        return authorName;
    }

    // Start of user code getterAnnotation:content
    // End of user code
    @OslcName("content")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "content")
    @OslcDescription("The content of the comment.")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(true)
    @OslcTitle("Content")
    public String getContent()
    {
        // Start of user code getterInit:content
        // End of user code
        return content;
    }

    // Start of user code getterAnnotation:created
    // End of user code
    @OslcName("created")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "created")
    @OslcDescription("The date when the comment was created.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.DateTime)
    @OslcReadOnly(true)
    @OslcTitle("Created")
    public Date getCreated()
    {
        // Start of user code getterInit:created
        // End of user code
        return created;
    }

    // Start of user code getterAnnotation:isPrivate
    // End of user code
    @OslcName("isPrivate")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "isPrivate")
    @OslcDescription("Whether the comment is private.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.Boolean)
    @OslcReadOnly(true)
    @OslcTitle("Private")
    public Boolean getIsPrivate()
    {
        // Start of user code getterInit:isPrivate
        // End of user code
        return isPrivate;
    }

    // Start of user code setterAnnotation:commentId
    // End of user code
    public void setCommentId(final String commentId)
    {
        // Start of user code setterInit:commentId
        // End of user code
        this.commentId = commentId;
        // Start of user code setterFinalize:commentId
        // End of user code
    }

    // Start of user code setterAnnotation:commentCount
    // End of user code
    public void setCommentCount(final Integer commentCount)
    {
        // Start of user code setterInit:commentCount
        // End of user code
        this.commentCount = commentCount;
        // Start of user code setterFinalize:commentCount
        // End of user code
    }

    // Start of user code setterAnnotation:author
    // End of user code
    public void setAuthor(final String author)
    {
        // Start of user code setterInit:author
        // End of user code
        this.author = author;
        // Start of user code setterFinalize:author
        // End of user code
    }

    // Start of user code setterAnnotation:authorName
    // End of user code
    public void setAuthorName(final String authorName)
    {
        // Start of user code setterInit:authorName
        // End of user code
        this.authorName = authorName;
        // Start of user code setterFinalize:authorName
        // End of user code
    }

    // Start of user code setterAnnotation:content
    // End of user code
    public void setContent(final String content)
    {
        // Start of user code setterInit:content
        // End of user code
        this.content = content;
        // Start of user code setterFinalize:content
        // End of user code
    }

    // Start of user code setterAnnotation:created
    // End of user code
    public void setCreated(final Date created)
    {
        // Start of user code setterInit:created
        // End of user code
        this.created = created;
        // Start of user code setterFinalize:created
        // End of user code
    }

    // Start of user code setterAnnotation:isPrivate
    // End of user code
    public void setIsPrivate(final Boolean isPrivate)
    {
        // Start of user code setterInit:isPrivate
        // End of user code
        this.isPrivate = isPrivate;
        // Start of user code setterFinalize:isPrivate
        // End of user code
    }

}
