// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package se.kth.md.it.bcm.resources;

// spotless:off
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code
// spotless:on

public interface BugzDomainConstants
{
    // Start of user code user constants
    // End of user code

    /**
     * @deprecated use {@link BugzDomainConstants#BUGZILLA_NAMSPACE} or {@link BugzDomainConstants#BUGZILLA_DOMAIN_NAME} instead
     */
    @Deprecated(since = "5.0.1")
    public static String BUGZILLA_DOMAIN = "http://www.bugzilla.org/rdf#";
    public static String BUGZILLA_DOMAIN_NAME = "Bugzilla";
    public static String BUGZILLA_NAMSPACE = "http://www.bugzilla.org/rdf#"; //Vocabulary namespace for the resources and resource properties, when no explicit vocabulary (describes, or propertyDefinition) is defined 
    public static String BUGZILLA_NAMSPACE_PREFIX = "bugz"; //Vocabulary prefix for the resources and resource properties, when no explicit vocabulary (describes, or propertyDefinition) is defined

    public static String BUGZILLACHANGEREQUEST_PATH = "bugzillaChangeRequest";  //the relative path of the resource shape URL.
    public static String BUGZILLACHANGEREQUEST_NAMESPACE = BugzDomainConstants.BUGZILLA_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String BUGZILLACHANGEREQUEST_LOCALNAME = "BugzillaChangeRequest"; //localName of the rdfs:class the resource describes
    public static String BUGZILLACHANGEREQUEST_TYPE = BUGZILLACHANGEREQUEST_NAMESPACE + BUGZILLACHANGEREQUEST_LOCALNAME; //fullname of the rdfs:class the resource describes
}
