// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package se.kth.md.it.bcm.resources;

// spotless:off
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code
// spotless:on

public interface DctermsDomainConstants
{
    // Start of user code user constants
    // End of user code

    /**
     * @deprecated use {@link DctermsDomainConstants#DUBLIN_CORE_NAMSPACE} or {@link DctermsDomainConstants#DUBLIN_CORE_DOMAIN_NAME} instead
     */
    @Deprecated(since = "5.0.1")
    public static String DUBLIN_CORE_DOMAIN = "http://purl.org/dc/terms/";
    public static String DUBLIN_CORE_DOMAIN_NAME = "Dublin Core";
    public static String DUBLIN_CORE_NAMSPACE = "http://purl.org/dc/terms/"; //Vocabulary namespace for the resources and resource properties, when no explicit vocabulary (describes, or propertyDefinition) is defined 
    public static String DUBLIN_CORE_NAMSPACE_PREFIX = "dcterms"; //Vocabulary prefix for the resources and resource properties, when no explicit vocabulary (describes, or propertyDefinition) is defined

    public static String TYPE_PATH = "type";  //the relative path of the resource shape URL.
    public static String TYPE_NAMESPACE = DctermsDomainConstants.DUBLIN_CORE_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String TYPE_LOCALNAME = "Type"; //localName of the rdfs:class the resource describes
    public static String TYPE_TYPE = TYPE_NAMESPACE + TYPE_LOCALNAME; //fullname of the rdfs:class the resource describes
}
