// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package se.kth.md.it.bcm.resources;

// spotless:off
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.Iterator;

import org.eclipse.lyo.oslc4j.core.annotation.OslcAllowedValue;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDescription;
import org.eclipse.lyo.oslc4j.core.annotation.OslcMemberProperty;
import org.eclipse.lyo.oslc4j.core.annotation.OslcName;
import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespace;
import org.eclipse.lyo.oslc4j.core.annotation.OslcOccurs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRdfCollectionType;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRange;
import org.eclipse.lyo.oslc4j.core.annotation.OslcReadOnly;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRepresentation;
import org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape;
import org.eclipse.lyo.oslc4j.core.annotation.OslcTitle;
import org.eclipse.lyo.oslc4j.core.annotation.OslcValueType;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.Occurs;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.Representation;
import org.eclipse.lyo.oslc4j.core.model.ValueType;

import se.kth.md.it.bcm.resources.BugzDomainConstants;
import se.kth.md.it.bcm.resources.BugzDomainConstants;
import se.kth.md.it.bcm.resources.IPerson;
import se.kth.md.it.bcm.resources.IType;
// Start of user code imports
// End of user code
// spotless:on

@OslcNamespace(BugzDomainConstants.BUGZILLACHANGEREQUEST_NAMESPACE)
@OslcName(BugzDomainConstants.BUGZILLACHANGEREQUEST_LOCALNAME)
@OslcResourceShape(title = "BugzillaChangeRequest Shape", describes = BugzDomainConstants.BUGZILLACHANGEREQUEST_TYPE)
public interface IBugzillaChangeRequest
{


    @OslcName("priority")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "priority")
    @OslcDescription("The Bugzilla priority for this change request.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    @OslcTitle("Priority")
    public String getPriority();

    @OslcName("platform")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "platform")
    @OslcDescription("The Bugzilla platform for this change request.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    @OslcTitle("Platform")
    public String getPlatform();

    @OslcName("version")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "version")
    @OslcDescription("The Bugzilla version for this change request.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(true)
    @OslcTitle("Version")
    public String getVersion();

    @OslcName("component")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "component")
    @OslcDescription("The Bugzilla product definition for this change request.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    @OslcTitle("Component")
    public String getComponent();

    @OslcName("product")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "product")
    @OslcDescription("")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    public String getProduct();

    @OslcName("operatingSystem")
    @OslcPropertyDefinition(BugzDomainConstants.BUGZILLA_NAMSPACE + "operatingSystem")
    @OslcDescription("The Bugzilla operating system for this change request.")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    @OslcTitle("Operating System")
    public String getOperatingSystem();


    public void setPriority(final String priority );
    public void setPlatform(final String platform );
    public void setVersion(final String version );
    public void setComponent(final String component );
    public void setProduct(final String product );
    public void setOperatingSystem(final String operatingSystem );
}

