// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package se.kth.md.it.bcm.resources;

// spotless:off
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code
// spotless:on

public interface Oslc_cmDomainConstants
{
    // Start of user code user constants
    // End of user code

    /**
     * @deprecated use {@link Oslc_cmDomainConstants#CHANGE_MANAGEMENT_NAMSPACE} or {@link Oslc_cmDomainConstants#CHANGE_MANAGEMENT_DOMAIN_NAME} instead
     */
    @Deprecated(since = "5.0.1")
    public static String CHANGE_MANAGEMENT_DOMAIN = "http://open-services.net/ns/cm#";
    public static String CHANGE_MANAGEMENT_DOMAIN_NAME = "Change_Management";
    public static String CHANGE_MANAGEMENT_NAMSPACE = "http://open-services.net/ns/cm#"; //Vocabulary namespace for the resources and resource properties, when no explicit vocabulary (describes, or propertyDefinition) is defined 
    public static String CHANGE_MANAGEMENT_NAMSPACE_PREFIX = "oslc_cm"; //Vocabulary prefix for the resources and resource properties, when no explicit vocabulary (describes, or propertyDefinition) is defined

    public static String CHANGEREQUEST_PATH = "changeRequest";  //the relative path of the resource shape URL.
    public static String CHANGEREQUEST_NAMESPACE = Oslc_cmDomainConstants.CHANGE_MANAGEMENT_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String CHANGEREQUEST_LOCALNAME = "ChangeRequest"; //localName of the rdfs:class the resource describes
    public static String CHANGEREQUEST_TYPE = CHANGEREQUEST_NAMESPACE + CHANGEREQUEST_LOCALNAME; //fullname of the rdfs:class the resource describes
}
