/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Michael Fiedler     - initial API and implementation for Bugzilla adapter
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
package se.kth.md.it.bcm.services;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;

import jakarta.servlet.RequestDispatcher;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.WebApplicationException;
import jakarta.ws.rs.core.Context;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.Response.Status;
import jakarta.ws.rs.core.UriInfo;

import org.eclipse.lyo.oslc4j.core.annotation.OslcQueryCapability;
import org.eclipse.lyo.oslc4j.core.annotation.OslcService;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.OslcMediaType;

import se.kth.md.it.bcm.BugzillaLyoArchivesConstants;
import se.kth.md.it.bcm.bugzilla.Bug;
import se.kth.md.it.bcm.bugzilla.BugzillaArchive;
import se.kth.md.it.bcm.bugzilla.Comment;
import se.kth.md.it.bcm.resources.BugzillaComment;

// Start of user code imports
import jakarta.inject.Inject;
import se.kth.md.it.bcm.ResourcesFactory;
// End of user code

// Start of user code pre_class_code
// End of user code

@OslcService(BugzillaLyoArchivesConstants.BUGZILLA_DOMAIN)
@Path("serviceProviders/{serviceProviderId}/bugzillaComments")
public class BugzillaCommentService
{
	@Context private HttpServletRequest httpServletRequest;
	@Context private HttpServletResponse httpServletResponse;
	@Context private UriInfo uriInfo;
	
	@Inject private ResourcesFactory resourcesFactory;

	// Start of user code class_attributes
	// End of user code
	
	// Start of user code class_methods
	// End of user code
	
	public BugzillaCommentService()
	{
		super();
	}

	/**
	 * RDF/XML, XML and JSON representation of a comment collection
	 * 
	 * @param where
	 * @param pageString
	 * @return
	 * @throws IOException
	 * @throws ServletException
	 */
	@OslcQueryCapability
	(
		 title = "QueryCapability for Bugzilla Comments",
		 label = "Bugzilla Comments Query",
		 resourceShape = OslcConstants.PATH_RESOURCE_SHAPES + "/" + "bugzillaComment",
		 resourceTypes = {BugzillaLyoArchivesConstants.BUGZILLA_NAMSPACE + "comment"},
		 usages = {OslcConstants.OSLC_USAGE_DEFAULT}
	) 
	@GET 
	@Path("query")
	@Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON})
	public BugzillaComment[] queryBugzillaComments(
								@PathParam("serviceProviderId") final String serviceProviderId ,
								@QueryParam("oslc.where") final String where,
								@QueryParam("page") final String pageString,
								@QueryParam("limit") final String limitString) throws IOException, ServletException 
	{
		int page=0;
		int limit=20;
		if (null != pageString) {
			page = Integer.parseInt(pageString);
		}
		if (null != limitString) {
			limit = Integer.parseInt(limitString);
		}
		
		// Start of user code queryBugzillaComments
		// End of user code

		final List<BugzillaComment> resources = new ArrayList<>();
		return resources.toArray(new BugzillaComment[resources.size()]);
	}

	/**
	 * HTML representation of comment collection
	 * 
	 * @param pageString
	 * @return
	 * @throws ServletException
	 * @throws IOException
	 */
	@GET
	@Path("query")
	@Produces({ MediaType.TEXT_HTML })
	public Response queryBugzillaCommentsAsHtml(
								@PathParam("serviceProviderId") final String serviceProviderId ,
								@QueryParam("oslc.where") final String where,
								@QueryParam("page") final String pageString,
								@QueryParam("limit") final String limitString) throws ServletException, IOException
	{
		int page=0;
		int limit=20;
		if (null != pageString) {
			page = Integer.parseInt(pageString);
		}
		if (null != limitString) {
			limit = Integer.parseInt(limitString);
		}

		// Start of user code queryBugzillaCommentsAsHtml
		// End of user code

		final List<BugzillaComment> resources = new ArrayList<>();

		if (resources!= null) {
			httpServletRequest.setAttribute("resources", resources);
			// Start of user code queryBugzillaCommentsAsHtml_setAttributes
			// End of user code

			httpServletRequest.setAttribute("queryUri", 
					uriInfo.getAbsolutePath().toString() + "?oslc.paging=true");
			if (resources.size() > limit) {
				resources.remove(resources.size() - 1);
				httpServletRequest.setAttribute("nextPageUri", 
					uriInfo.getAbsolutePath().toString() + "?oslc.paging=true&amp;page=" + (page + 1));
				}
				RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/se/kth/md/it/bcm/bugzillacommentscollection.jsp");
				rd.forward(httpServletRequest,httpServletResponse);
		}
		
		throw new WebApplicationException(Status.NOT_FOUND);	
	}



	/**
	 * RDF/XML, XML and JSON representation of comments for a specific bug
	 * 
	 * @return
	 * @throws IOException
	 * @throws ServletException
	 * @throws URISyntaxException
	 */
	@GET
	@Path("bugz/{bugId}/comments")
	@Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON})
	public BugzillaComment[] getBugComments(
			@PathParam("serviceProviderId") final String serviceProviderId, 
			@PathParam("bugId") final String bugId
		) throws IOException, ServletException, URISyntaxException
	{
		// Start of user code getBugComments_init
		// End of user code

		Bug bug = BugzillaArchive.getInstance().getBug(Integer.parseInt(bugId));
		if (bug == null) {
			throw new WebApplicationException(Status.NOT_FOUND);
		}

		List<BugzillaComment> comments = new ArrayList<>();
		int commentIndex = 0;
		for (Comment bugComment : bug.getComments()) {
			// Skip private comments if we want to filter them
			if (!bugComment.isPrivate()) {
				BugzillaComment commentResource = resourcesFactory.createBugzillaComment(bugId, String.valueOf(bugComment.getCommentId()));
				commentResource.setCommentId(String.valueOf(bugComment.getCommentId()));
				commentResource.setCommentCount(bugComment.getCommentCount());
				commentResource.setContent(bugComment.getThetext());
				commentResource.setAuthor(bugComment.getWho());
				commentResource.setAuthorName(bugComment.getWhoName());
				commentResource.setCreated(bugComment.getBugWhen());
				commentResource.setIsPrivate(bugComment.isPrivate());
				comments.add(commentResource);
				commentIndex++;
			}
		}

		if (comments != null && !comments.isEmpty()) {
			// Start of user code getBugComments
			// End of user code
			return comments.toArray(new BugzillaComment[comments.size()]);
		}

		throw new WebApplicationException(Status.NOT_FOUND);
	}
	
	/**
	 * RDF/XML, XML and JSON representation of a single comment
	 * 
	 * @return
	 * @throws IOException
	 * @throws ServletException
	 * @throws URISyntaxException
	 */
	@GET
	@Path("bugz/{bugId}/comments/{commentId}")
	@Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON})
	public BugzillaComment getBugComment(
			@PathParam("serviceProviderId") final String serviceProviderId, 
			@PathParam("bugId") final String bugId,
			@PathParam("commentId") final String commentId
		) throws IOException, ServletException, URISyntaxException
	{
		// Start of user code getBugComment_init
		// End of user code

		Bug bug = BugzillaArchive.getInstance().getBug(Integer.parseInt(bugId));
		if (bug == null) {
			throw new WebApplicationException(Status.NOT_FOUND);
		}

		BugzillaComment commentResource = null;
		for (Comment bugComment : bug.getComments()) {
			if (bugComment.getCommentId() == Integer.parseInt(commentId)) {
				commentResource = resourcesFactory.createBugzillaComment(bugId, commentId);
				commentResource.setCommentId(String.valueOf(bugComment.getCommentId()));
				commentResource.setCommentCount(bugComment.getCommentCount());
				commentResource.setContent(bugComment.getThetext());
				commentResource.setAuthor(bugComment.getWho());
				commentResource.setAuthorName(bugComment.getWhoName());
				commentResource.setCreated(bugComment.getBugWhen());
				commentResource.setIsPrivate(bugComment.isPrivate());
				break;
			}
		}

		if (commentResource != null) {
			// Start of user code getBugComment
			// End of user code
			return commentResource;
		}

		throw new WebApplicationException(Status.NOT_FOUND);
	}


}
