/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Michael Fiedler     - initial API and implementation for Bugzilla adapter
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
package se.kth.md.it.bcm.services;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;

import jakarta.servlet.RequestDispatcher;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.WebApplicationException;
import jakarta.ws.rs.core.Context;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.Response.Status;
import jakarta.ws.rs.core.UriInfo;

import org.eclipse.lyo.oslc4j.core.annotation.OslcQueryCapability;
import org.eclipse.lyo.oslc4j.core.annotation.OslcService;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.OslcMediaType;

import se.kth.md.it.bcm.BugzillaLyoArchivesConstants;
import se.kth.md.it.bcm.resources.BugzillaChangeRequest;

// Start of user code imports
// End of user code

// Start of user code pre_class_code
// End of user code

@OslcService(BugzillaLyoArchivesConstants.BUGZILLA_DOMAIN)
@Path("serviceProviders/{serviceProviderId}/bugzillaChangeRequests")
public class BugzillaChangeRequestService
{
	@Context private HttpServletRequest httpServletRequest;
	@Context private HttpServletResponse httpServletResponse;
	@Context private UriInfo uriInfo;

	// Start of user code class_attributes
	// End of user code
	
	// Start of user code class_methods
	// End of user code
	
    public BugzillaChangeRequestService()
    {
        super();
    }

    /**
     * RDF/XML, XML and JSON representation of a change request collection
     * 
     * TODO:  add query support
     * 
     * @param where
     * @param pageString
     * @return
     * @throws IOException
     * @throws ServletException
     */
    @OslcQueryCapability
    (
        title = "QueryCapability1",
        label = "QueryCapability1",
        resourceShape = OslcConstants.PATH_RESOURCE_SHAPES + "/" + BugzillaLyoArchivesConstants.PATH_BUGZILLACHANGEREQUEST,
        resourceTypes = {BugzillaLyoArchivesConstants.TYPE_BUGZILLACHANGEREQUEST},
        usages = {OslcConstants.OSLC_USAGE_DEFAULT}
    ) 
    @GET 
    @Path("query")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON})
    public BugzillaChangeRequest[] queryBugzillaChangeRequests(
													@PathParam("serviceProviderId") final String serviceProviderId ,
    		                                 		@QueryParam("oslc.where") final String where,
    		                                 		@QueryParam("page") final String pageString,
													@QueryParam("limit") final String limitString) throws IOException, ServletException 
    {
		int page=0;
		int limit=20;
		if (null != pageString) {
			page = Integer.parseInt(pageString);
		}
		if (null != limitString) {
			limit = Integer.parseInt(limitString);
		}
        
		// Start of user code queryBugzillaChangeRequests
		// End of user code

		// fixme inject instance
//        final List<BugzillaChangeRequest> resources = RestDelegate.queryBugzillaChangeRequests(httpServletRequest, serviceProviderId, where, page, limit);
        final List<BugzillaChangeRequest> resources = new ArrayList<>();
        return resources.toArray(new BugzillaChangeRequest [resources.size()]);
    }

    /**
     * HTML representation of change request collection
     * 
     * Forwards to changerequest_collection_html.jsp to build the html page
     * 
     * @param pageString
     * @return
     * @throws ServletException
     * @throws IOException
     */
	@GET
    @Path("query")
	@Produces({ MediaType.TEXT_HTML })
	public Response queryBugzillaChangeRequestsAsHtml(
									@PathParam("serviceProviderId") final String serviceProviderId ,
                               		@QueryParam("oslc.where") final String where,
                               		@QueryParam("page") final String pageString,
			                        @QueryParam("limit") final String limitString) throws ServletException, IOException
	{
		int page=0;
		int limit=20;
		if (null != pageString) {
			page = Integer.parseInt(pageString);
		}
		if (null != limitString) {
			limit = Integer.parseInt(limitString);
		}

		// Start of user code queryBugzillaChangeRequestsAsHtml
		// End of user code

		// fixme inject instance
//        final List<BugzillaChangeRequest> resources = RestDelegate.queryBugzillaChangeRequests(httpServletRequest, serviceProviderId, where, page, limit);
        final List<BugzillaChangeRequest> resources = new ArrayList<>();

        if (resources!= null) {
        	httpServletRequest.setAttribute("resources", resources);
			// Start of user code queryBugzillaChangeRequestsAsHtml_setAttributes
			// End of user code

        	httpServletRequest.setAttribute("queryUri", 
                    uriInfo.getAbsolutePath().toString() + "?oslc.paging=true");
        	if (resources.size() > limit) {
        		resources.remove(resources.size() - 1);
        		httpServletRequest.setAttribute("nextPageUri", 
        				uriInfo.getAbsolutePath().toString() + "?oslc.paging=true&amp;page=" + (page + 1));
        	}
        	RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/se/kth/md/it/bcm/bugzillachangerequestscollection.jsp");
        	rd.forward(httpServletRequest,httpServletResponse);
        }
		
		throw new WebApplicationException(Status.NOT_FOUND);	
	}




	/**
	 * RDF/XML, XML and JSON representation of a single change request
	 * 
	 * @return
	 * @throws IOException
	 * @throws ServletException
	 * @throws URISyntaxException
	 */
    @GET
    @Path("{bugzillaChangeRequestId}")
    @Produces({OslcMediaType.APPLICATION_RDF_XML, OslcMediaType.APPLICATION_XML, OslcMediaType.APPLICATION_JSON})
    public BugzillaChangeRequest getBugzillaChangeRequest(
                @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("bugzillaChangeRequestId") final String bugzillaChangeRequestId
        ) throws IOException, ServletException, URISyntaxException
    {
		// Start of user code getResource_init
		// End of user code


		// fixme
//        final BugzillaChangeRequest aBugzillaChangeRequest = RestDelegate.getBugzillaChangeRequest(httpServletRequest, serviceProviderId, bugzillaChangeRequestId);
        final BugzillaChangeRequest aBugzillaChangeRequest = null;

        if (aBugzillaChangeRequest != null) {
			// Start of user code getBugzillaChangeRequest
			// End of user code
            return aBugzillaChangeRequest;
        }

        throw new WebApplicationException(Status.NOT_FOUND);
    }
    
    /**
     * 
     * HTML representation for a single change request  - redirect the request directly to Bugzilla
     * 
     * @throws ServletException
     * @throws IOException
     * @throws URISyntaxException
     */
	@GET
    @Path("{bugzillaChangeRequestId}")
	@Produces({ MediaType.TEXT_HTML })
	public Response getBugzillaChangeRequestAsHtml(
        @PathParam("serviceProviderId") final String serviceProviderId, @PathParam("bugzillaChangeRequestId") final String bugzillaChangeRequestId
        ) throws ServletException, IOException, URISyntaxException
	{	
		// Start of user code getBugzillaChangeRequestAsHtml_init
		// End of user code

		// fixme
//        final BugzillaChangeRequest aBugzillaChangeRequest = RestDelegate.getBugzillaChangeRequest(httpServletRequest, serviceProviderId, bugzillaChangeRequestId);
        final BugzillaChangeRequest aBugzillaChangeRequest = null;

        if (aBugzillaChangeRequest != null) {
        	httpServletRequest.setAttribute("aBugzillaChangeRequest", aBugzillaChangeRequest);
			// Start of user code getBugzillaChangeRequestAsHtml_setAttributes
			// End of user code

        	RequestDispatcher rd = httpServletRequest.getRequestDispatcher("/se/kth/md/it/bcm/bugzillachangerequest.jsp");
        	rd.forward(httpServletRequest,httpServletResponse);
		}

        throw new WebApplicationException(Status.NOT_FOUND);
	}

}
