<%--To avoid the overriding of any manual code changes upon subsequent code generations, disable "Generate JSP Files" option in the Adaptor model.--%>
<!DOCTYPE html>
<%--
 Copyright (c) 2022 Contributors to the Eclipse Foundation
 
 See the NOTICE file(s) distributed with this work for additional
 information regarding copyright ownership.
 
 This program and the accompanying materials are made available under the
 terms of the Eclipse Distribution License 1.0 which is available at
 http://www.eclipse.org/org/documents/edl-v10.php.
 
 SPDX-License-Identifier: BSD-3-Simple

 This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
--%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>

<%@page import="jakarta.ws.rs.core.UriBuilder"%>
<%@page import="org.eclipse.lyo.oslc4j.core.OSLC4JUtils"%>
<%@page import="org.eclipse.lyo.oslc4j.core.model.ServiceProvider"%>
<%@page import="org.eclipse.lyo.oslc4j.core.model.AbstractResource"%>
<%@page import="org.eclipse.lyo.oslc4j.core.OSLC4JConstants"%>
<%@page import="java.util.List" %>

<%@page import="se.kth.md.it.bcm.resources.BugzillaChangeRequest"%>
<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>
<%
  List<BugzillaChangeRequest> resources = (List<BugzillaChangeRequest>) request.getAttribute("resources");
  String queryUri = (String)request.getAttribute("queryUri");
  String nextPageUri = (String)request.getAttribute(OSLC4JConstants.OSLC4J_NEXT_PAGE);
  String catalogUrl = UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path("/catalog/singleton").build().toString();
%>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bugzilla Change Requests</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  <link href="<c:url value="/static/css/adaptor.css"/>" rel="stylesheet">
  <script src="<c:url value="/static/js/ui-preview-helper.js"/>"></script>
  <script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
      setupUiPreviewOnPopover(document.querySelectorAll("a.oslc-resource-link"));
    });
  </script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;400;500;600&display=swap" rel="stylesheet">
  <style>
      body {
          font-family: 'Fira Sans', sans-serif;
          background-color: #f8f9fa;
      }
      .page-header {
          margin-bottom: 2rem;
      }
      .card {
          box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075);
          border: none;
          margin-bottom: 2rem;
      }
      .card-header {
          background-color: #fff;
          border-bottom: 1px solid #eee;
          font-weight: 600;
          cursor: pointer;
      }
  </style>

</head>
<body>
<!-- Fixed navbar -->
  <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="<c:url value="/"/>"><%= application.getServletContextName() %></a>
      <ul class="navbar-nav me-auto">
        <li class="nav-item"><a class="nav-link" href="<c:url value="<%= catalogUrl %>"/>">Service Provider Catalog</a></li>
        <li class="nav-item"><a class="nav-link" href="<c:url value="/swagger-ui/index.jsp"/>">Swagger UI</a></li>
      </ul>
    </div>
  </nav>
  <!-- Begin page content -->
  <div class="container">
    <div class="page-header">
      <h1>Bugzilla Change Requests</h1>
      <div class="alert alert-info" role="alert">
          Showing ${resources.size()} resources on this page
          <% if (nextPageUri != null) { %>
            | <a href="<%= nextPageUri %>">Next Page &raquo;</a>
          <% } %>
      </div>
    </div>
        <c:forEach items="${resources}" var="res">
          <div class="card mb-3">
            <div class="card-body">
              <div class="row">
                <div class="col-md-10">
                  <h5 class="card-title">
                    <a href="${fn:escapeXml(res.getAbout())}" class="oslc-resource-link">${fn:escapeXml(res.getIdentifier())}: ${fn:escapeXml(res.getTitle())}</a>
                  </h5>
                </div>
                <div class="col-md-2 text-end">
                  <c:choose>
                    <c:when test="${res.status == 'NEW' || res.status == 'UNCONFIRMED'}">
                      <c:choose>
                        <c:when test="${fn:contains(res.subject, 'Status: Abandoned')}">
                          <span class="badge rounded-pill bg-warning text-dark">${fn:escapeXml(res.status)}</span>
                        </c:when>
                        <c:otherwise>
                          <span class="badge rounded-pill bg-primary">${fn:escapeXml(res.status)}</span>
                        </c:otherwise>
                      </c:choose>
                    </c:when>
                    <c:when test="${res.status == 'RESOLVED' || res.status == 'VERIFIED'}">
                      <span class="badge rounded-pill bg-success">${fn:escapeXml(res.status)}</span>
                    </c:when>
                    <c:when test="${res.status == 'CLOSED'}">
                      <span class="badge rounded-pill bg-dark">${fn:escapeXml(res.status)}</span>
                    </c:when>
                    <c:when test="${res.status == 'IN_PROGRESS' || res.status == 'ASSIGNED'}">
                      <span class="badge rounded-pill bg-info text-dark">${fn:escapeXml(res.status)}</span>
                    </c:when>
                    <c:otherwise>
                      <span class="badge rounded-pill bg-secondary">${fn:escapeXml(res.status)}</span>
                    </c:otherwise>
                  </c:choose>
                </div>
              </div>
              <div class="row mt-2">
                <div class="col-md-12">
                  <small class="text-muted">
                    ${fn:escapeXml(res.getProduct())} / ${fn:escapeXml(res.getComponent())} &
                    Priority: <c:out value="${res.priority}"/>
                    <c:if test="${not empty res.subject}">
                      | <c:forEach items="${res.subject}" var="subject">
                          <c:choose>
                            <c:when test="${subject == 'Status: Abandoned'}">
                              <span class="badge rounded-pill bg-danger me-1">${fn:escapeXml(subject)}</span>
                            </c:when>
                            <c:otherwise>
                              <span class="badge rounded-pill bg-secondary me-1">${fn:escapeXml(subject)}</span>
                            </c:otherwise>
                          </c:choose>
                        </c:forEach>
                    </c:if>
                  </small>
                </div>
              </div>
            </div>
          </div>
        </c:forEach>
      </div>
  <footer class="footer">
      <div class="container">
          <p class="text-muted">OSLC Adaptor was generated using <a href="http://eclipse.org/lyo">Eclipse Lyo</a>.</p>
      </div>
  </footer>
</body>
</html>
