<%--To avoid the overriding of any manual code changes upon subsequent code generations, disable "Generate JSP Files" option in the Adaptor model.--%>
<!DOCTYPE html>
<%--
 Copyright (c) 2022 Contributors to the Eclipse Foundation
 
 See the NOTICE file(s) distributed with this work for additional
 information regarding copyright ownership.
 
 This program and the accompanying materials are made available under the
 terms of the Eclipse Distribution License 1.0 which is available at
 http://www.eclipse.org/org/documents/edl-v10.php.
 
 SPDX-License-Identifier: BSD-3-Simple

 This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
--%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>

<%@page import="org.eclipse.lyo.oslc4j.core.model.Link" %>
<%@page import="org.eclipse.lyo.oslc4j.core.model.ServiceProvider"%>
<%@page import="org.eclipse.lyo.oslc4j.core.model.OslcConstants"%>
<%@page import="org.eclipse.lyo.oslc4j.core.OSLC4JUtils"%>
<%@page import="org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition"%>
<%@page import="org.eclipse.lyo.oslc4j.core.annotation.OslcName"%>
<%@page import="java.lang.reflect.Method"%>
<%@page import="java.net.URI"%>
<%@page import="java.util.Collection"%>
<%@page import="java.util.Date"%>
<%@page import="java.util.HashSet"%>
<%@page import="java.util.List"%>
<%@page import="java.util.Iterator"%>
<%@page import="java.util.Map"%>
<%@page import="javax.xml.namespace.QName"%>
<%@page import="jakarta.ws.rs.core.UriBuilder"%>

<%@page import="se.kth.md.it.bcm.resources.BugzillaChangeRequest"%>
<%@page import="se.kth.md.it.bcm.resources.BugzDomainConstants"%>

<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>

<%
  BugzillaChangeRequest aBugzillaChangeRequest = (BugzillaChangeRequest) request.getAttribute("aBugzillaChangeRequest");
%>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= aBugzillaChangeRequest.toString() %></title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #ffffff;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        }
        .preview-container {
            padding: 12px;
            height: 100%;
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }
        .status-row {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 8px;
            border-bottom: 1px solid #e9ecef;
            padding-bottom: 6px;
        }
        .meta-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 8px 16px;
            font-size: 0.8rem;
            color: #333333;
        }
        .meta-item {
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }
        .meta-label {
            font-weight: 600;
            color: #6c757d;
            margin-right: 4px;
        }
        .preview-footer {
            border-top: 1px solid #e9ecef;
            padding-top: 6px;
            margin-top: 8px;
            display: flex;
            justify-content: space-between;
            font-size: 0.72rem;
            color: #868e96;
        }
    </style>
</head>

<body>
<%
String status = aBugzillaChangeRequest.getStatus() != null ? aBugzillaChangeRequest.getStatus() : "Unknown";
String statusBadgeClass = "bg-secondary text-white";
if (status.equalsIgnoreCase("new") || status.equalsIgnoreCase("assigned") || status.equalsIgnoreCase("reopened")) {
    statusBadgeClass = "bg-primary text-white";
} else if (status.equalsIgnoreCase("resolved") || status.equalsIgnoreCase("verified")) {
    statusBadgeClass = "bg-success text-white";
}

String priority = aBugzillaChangeRequest.getPriority() != null ? aBugzillaChangeRequest.getPriority() : "n/a";
String priorityBadgeClass = "bg-secondary text-white";
if (priority.equalsIgnoreCase("P1") || priority.equalsIgnoreCase("high") || priority.equalsIgnoreCase("highest")) {
    priorityBadgeClass = "bg-danger text-white";
} else if (priority.equalsIgnoreCase("P2") || priority.equalsIgnoreCase("normal")) {
    priorityBadgeClass = "bg-warning text-dark";
} else if (priority.equalsIgnoreCase("P3") || priority.equalsIgnoreCase("low")) {
    priorityBadgeClass = "bg-light text-dark border";
}

String creatorName = "unnamed";
if (aBugzillaChangeRequest.getCreator() != null && !aBugzillaChangeRequest.getCreator().isEmpty()) {
    se.kth.md.it.bcm.resources.Person creator = aBugzillaChangeRequest.getCreator().iterator().next();
    if (creator != null) {
        if (creator.getName() != null) {
            creatorName = creator.getName();
        } else if (creator.getGivenName() != null || creator.getFamilyName() != null) {
            creatorName = (creator.getGivenName() != null ? creator.getGivenName() : "") 
                        + (creator.getGivenName() != null && creator.getFamilyName() != null ? " " : "") 
                        + (creator.getFamilyName() != null ? creator.getFamilyName() : "");
        }
    }
}
%>
<div class="preview-container">
    <div class="status-row">
        <span class="meta-label" style="font-size: 0.85rem;">Status:</span>
        <span class="badge <%= statusBadgeClass %>" style="font-size: 0.75rem;"><%= status %></span>
    </div>
    
    <div class="meta-grid">
        <div class="meta-item">
            <span class="meta-label">Product:</span>
            <%= aBugzillaChangeRequest.getProduct() != null ? aBugzillaChangeRequest.getProduct() : "n/a" %>
        </div>
        <div class="meta-item">
            <span class="meta-label">Component:</span>
            <%= aBugzillaChangeRequest.getComponent() != null ? aBugzillaChangeRequest.getComponent() : "n/a" %>
        </div>
        <div class="meta-item">
            <span class="meta-label">Priority:</span>
            <span class="badge <%= priorityBadgeClass %>" style="font-size: 0.7rem; padding: 2px 6px;"><%= priority %></span>
        </div>
        <div class="meta-item">
            <span class="meta-label">Platform:</span>
            <%= aBugzillaChangeRequest.getPlatform() != null ? aBugzillaChangeRequest.getPlatform() : "n/a" %>
        </div>
    </div>
    
    <div class="preview-footer">
        <span>Created: <%= aBugzillaChangeRequest.getCreated() != null ? new java.text.SimpleDateFormat("yyyy-MM-dd").format(aBugzillaChangeRequest.getCreated()) : "n/a" %></span>
        <span class="text-truncate" style="max-width: 130px;" title="Creator: <%= creatorName %>">By: <%= creatorName %></span>
    </div>
</div>
</body>
</html>
