<%--To avoid the overriding of any manual code changes upon subsequent code generations, disable "Generate JSP Files" option in the Adaptor model.--%>
<!DOCTYPE html>
<%--
 Copyright (c) 2021 Contributors to the Eclipse Foundation
 
 See the NOTICE file(s) distributed with this work for additional
 information regarding copyright ownership.
 
 This program and the accompanying materials are made available under the
 terms of the Eclipse Distribution License 1.0 which is available at
 http://www.eclipse.org/org/documents/edl-v10.php.
 
 SPDX-License-Identifier: BSD-3-Simple

 This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
--%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>

<%@page import="org.eclipse.lyo.oslc4j.core.model.Link" %>
<%@page import="org.eclipse.lyo.oslc4j.core.model.ServiceProvider"%>
<%@page import="org.eclipse.lyo.oslc4j.core.model.OslcConstants"%>
<%@page import="org.eclipse.lyo.oslc4j.core.OSLC4JUtils"%>
<%@page import="org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition"%>
<%@page import="org.eclipse.lyo.oslc4j.core.annotation.OslcName"%>
<%@page import="java.lang.reflect.Method"%>
<%@page import="java.net.URI"%>
<%@page import="java.util.Collection"%>
<%@page import="java.util.Date"%>
<%@page import="java.util.HashSet"%>
<%@page import="java.util.List"%>
<%@page import="java.util.Iterator"%>
<%@page import="java.util.Map"%>
<%@page import="javax.xml.namespace.QName"%>
<%@page import="jakarta.ws.rs.core.UriBuilder"%>

<%@page import="se.kth.md.it.bcm.resources.BugzillaChangeRequest"%>
<%@page import="se.kth.md.it.bcm.resources.BugzDomainConstants"%>

<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>

<%
  BugzillaChangeRequest aBugzillaChangeRequest = (BugzillaChangeRequest) request.getAttribute("aBugzillaChangeRequest");
  String catalogUrl = UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path("/catalog/singleton").build().toString();
%>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title><%= aBugzillaChangeRequest.toString() %></title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  <link href="<c:url value="/static/css/adaptor.css"/>" rel="stylesheet">

  <script src="<c:url value="/static/js/ui-preview-helper.js"/>"></script>
  <script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
      setupUiPreviewOnPopover(document.querySelectorAll("a.oslc-resource-link"));
    });
  </script>
</head>

<body>
<!-- Fixed navbar -->
  <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="<c:url value="/"/>"><%= application.getServletContextName() %></a>
      <ul class="navbar-nav me-auto">
        <li class="nav-item"><a class="nav-link" href="<c:url value="<%= catalogUrl %>"/>">Service Provider Catalog</a></li>
        <li class="nav-item"><a class="nav-link" href="<c:url value="/swagger-ui/index.jsp"/>">Swagger UI</a></li>
      </ul>
    </div>
  </nav>
<!-- Begin page content -->
<div class="container">
    <div class="page-header">
        <h1>BugzillaChangeRequest: <%= aBugzillaChangeRequest.toString() %></h1>
        <%
        URI shapeUri = UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path(OslcConstants.PATH_RESOURCE_SHAPES).path(BugzDomainConstants.BUGZILLACHANGEREQUEST_PATH).build();
        Collection<URI> types = aBugzillaChangeRequest.getTypes();   
        %>
        <p class="lead">Resource URI:&nbsp;
        <jsp:include page="/se/kth/md/it/bcm/bugzillachangerequesttohtml.jsp"></jsp:include>
        </p>
        <p class="lead">Shape:&nbsp;
        <a href="<%=shapeUri%>"><%=shapeUri%></a>
        </p>
        <p class="lead">rdf:type(s):</p>
        <ul>
        <%for (URI type : aBugzillaChangeRequest.getTypes()) {%>
        <li><a href="<%=type%>"><%=type%></a></li>
        <%}%>
        </ul>
    </div>
        <h2>Properties</h2>
        <div>
          <% Method method = null; %>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getPriority"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getPriority() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getPriority().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getPlatform"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getPlatform() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getPlatform().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getVersion"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getVersion() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getVersion().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getComponent"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getComponent() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getComponent().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getProduct"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getProduct() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getProduct().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getOperatingSystem"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getOperatingSystem() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getOperatingSystem().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getAffectedByDefect"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Link next : aBugzillaChangeRequest.getAffectedByDefect()) {
                if (next.getValue() == null) {
                    out.write("<li>" + "<em>null</em>" + "</li>");
                }
                else {
                    out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                }
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getAffectsPlanItem"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Link next : aBugzillaChangeRequest.getAffectsPlanItem()) {
                if (next.getValue() == null) {
                    out.write("<li>" + "<em>null</em>" + "</li>");
                }
                else {
                    out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                }
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getAffectsRequirement"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Link next : aBugzillaChangeRequest.getAffectsRequirement()) {
                if (next.getValue() == null) {
                    out.write("<li>" + "<em>null</em>" + "</li>");
                }
                else {
                    out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                }
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getAffectsTestResult"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Link next : aBugzillaChangeRequest.getAffectsTestResult()) {
                if (next.getValue() == null) {
                    out.write("<li>" + "<em>null</em>" + "</li>");
                }
                else {
                    out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                }
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getBlocksTestExecutionRecord"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Link next : aBugzillaChangeRequest.getBlocksTestExecutionRecord()) {
                if (next.getValue() == null) {
                    out.write("<li>" + "<em>null</em>" + "</li>");
                }
                else {
                    out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                }
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getContributor"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Object next : aBugzillaChangeRequest.getContributor()) {
                %>
                <li> 
                <jsp:include page="/se/kth/md/it/bcm/persontohtml.jsp">
                    <jsp:param name="asLocalResource" value="true"/>
                    </jsp:include>
                </li> 
                <%
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getCreator"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Object next : aBugzillaChangeRequest.getCreator()) {
                %>
                <li> 
                <jsp:include page="/se/kth/md/it/bcm/persontohtml.jsp">
                    <jsp:param name="asLocalResource" value="true"/>
                    </jsp:include>
                </li> 
                <%
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getDctermsType"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Object next : aBugzillaChangeRequest.getDctermsType()) {
                %>
                <li> 
                <jsp:include page="/se/kth/md/it/bcm/typetohtml.jsp">
                    <jsp:param name="asLocalResource" value="true"/>
                    </jsp:include>
                </li> 
                <%
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getImplementsRequirement"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Link next : aBugzillaChangeRequest.getImplementsRequirement()) {
                if (next.getValue() == null) {
                    out.write("<li>" + "<em>null</em>" + "</li>");
                }
                else {
                    out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                }
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getRelatedChangeRequest"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Link next : aBugzillaChangeRequest.getRelatedChangeRequest()) {
                if (next.getValue() == null) {
                    out.write("<li>" + "<em>null</em>" + "</li>");
                }
                else {
                    out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                }
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getRelatedTestCase"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Link next : aBugzillaChangeRequest.getRelatedTestCase()) {
                if (next.getValue() == null) {
                    out.write("<li>" + "<em>null</em>" + "</li>");
                }
                else {
                    out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                }
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getRelatedTestExecutionRecord"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Link next : aBugzillaChangeRequest.getRelatedTestExecutionRecord()) {
                if (next.getValue() == null) {
                    out.write("<li>" + "<em>null</em>" + "</li>");
                }
                else {
                    out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                }
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getRelatedTestPlan"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Link next : aBugzillaChangeRequest.getRelatedTestPlan()) {
                if (next.getValue() == null) {
                    out.write("<li>" + "<em>null</em>" + "</li>");
                }
                else {
                    out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                }
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getRelatedTestScript"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Link next : aBugzillaChangeRequest.getRelatedTestScript()) {
                if (next.getValue() == null) {
                    out.write("<li>" + "<em>null</em>" + "</li>");
                }
                else {
                    out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                }
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getSubject"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            Iterator<String> subjectItr = aBugzillaChangeRequest.getSubject().iterator();
            while(subjectItr.hasNext()) {
                out.write("<li>" + subjectItr.next().toString() + "</li>");
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getTestedByTestCase"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Link next : aBugzillaChangeRequest.getTestedByTestCase()) {
                if (next.getValue() == null) {
                    out.write("<li>" + "<em>null</em>" + "</li>");
                }
                else {
                    out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                }
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getTracksChangeSet"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Link next : aBugzillaChangeRequest.getTracksChangeSet()) {
                if (next.getValue() == null) {
                    out.write("<li>" + "<em>null</em>" + "</li>");
                }
                else {
                    out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                }
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getTracksRequirement"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            for(Link next : aBugzillaChangeRequest.getTracksRequirement()) {
                if (next.getValue() == null) {
                    out.write("<li>" + "<em>null</em>" + "</li>");
                }
                else {
                    out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                }
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getRdfType"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <ul>
            <%
            Iterator<URI> rdfTypeItr = aBugzillaChangeRequest.getRdfType().iterator();
            while(rdfTypeItr.hasNext()) {
                out.write("<li>" + rdfTypeItr.next().toString() + "</li>");
            }
            %>
            </ul>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("isApproved"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.isApproved() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.isApproved().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("isClosed"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.isClosed() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.isClosed().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getCloseDate"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getCloseDate() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getCloseDate().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getCreated"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getCreated() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getCreated().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getDescription"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getDescription() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getDescription().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getDiscussedBy"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if ((aBugzillaChangeRequest.getDiscussedBy() == null) || (aBugzillaChangeRequest.getDiscussedBy().getValue() == null)) {
                out.write("<em>null</em>");
            }
            else {
                out.write("<a href=\"" + aBugzillaChangeRequest.getDiscussedBy().getValue().toString() + "\" class=\"oslc-resource-link\">" + aBugzillaChangeRequest.getDiscussedBy().getValue().toString() + "</a>");
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("isFixed"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.isFixed() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.isFixed().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getIdentifier"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getIdentifier() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getIdentifier().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("isInprogress"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.isInprogress() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.isInprogress().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getInstanceShape"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if ((aBugzillaChangeRequest.getInstanceShape() == null) || (aBugzillaChangeRequest.getInstanceShape().getValue() == null)) {
                out.write("<em>null</em>");
            }
            else {
                out.write("<a href=\"" + aBugzillaChangeRequest.getInstanceShape().getValue().toString() + "\" class=\"oslc-resource-link\">" + aBugzillaChangeRequest.getInstanceShape().getValue().toString() + "</a>");
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getModified"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getModified() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getModified().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("isReviewed"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.isReviewed() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.isReviewed().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getServiceProvider"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getServiceProvider() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getServiceProvider().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getShortTitle"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getShortTitle() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getShortTitle().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getStatus"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getStatus() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getStatus().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("getTitle"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.getTitle() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.getTitle().toString());
            }
            %>
            
            </dd>
          </dl>
          <dl class="row">
            <% method = BugzillaChangeRequest.class.getMethod("isVerified"); %>
            <dt  class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
            <dd class="col-sm-9">
            <%
            if (aBugzillaChangeRequest.isVerified() == null) {
                out.write("<em>null</em>");
            }
            else {
                out.write(aBugzillaChangeRequest.isVerified().toString());
            }
            %>
            
            </dd>
          </dl>
        </div>
        <%
        Map<QName, Object> extendedProperties = aBugzillaChangeRequest.getExtendedProperties();
        if (!extendedProperties.isEmpty()) {
        %>
            <h3>Extended Properties</h3>
            <div>
            <%
            for (Map.Entry<QName, Object> entry : extendedProperties.entrySet()) 
            {
                QName key = entry.getKey();
                Object value = entry.getValue();
            %>
            <dl class="row">
                <dt  class="col-sm-2 text-end"><a href="<%=key.getNamespaceURI() + key.getLocalPart() %>"><%=key.getLocalPart()%></a></dt>
                <dd class="col-sm-9"><%= value.toString()%></dd>
            </dl>
            <%
            }
            %>
            </div>
        <%
        }
        %>
</div>
  <footer class="footer">
    <div class="container">
      <p class="text-muted">
        OSLC Adaptor was generated using <a href="http://eclipse.org/lyo">Eclipse Lyo</a>.
      </p>
    </div>
  </footer>
</body>
</html>
