<%--To avoid the overriding of any manual code changes upon subsequent code generations, disable "Generate JSP Files" option in the Adaptor model.--%>
<!DOCTYPE html>
<%--
 Copyright (c) 2021 Contributors to the Eclipse Foundation
 
 See the NOTICE file(s) distributed with this work for additional
 information regarding copyright ownership.
 
 This program and the accompanying materials are made available under the
 terms of the Eclipse Distribution License 1.0 which is available at
 http://www.eclipse.org/org/documents/edl-v10.php.
 
 SPDX-License-Identifier: BSD-3-Simple

 This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
--%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>

<%@page import="org.eclipse.lyo.oslc4j.core.model.Link" %>
<%@page import="org.eclipse.lyo.oslc4j.core.model.ServiceProvider"%>
<%@page import="org.eclipse.lyo.oslc4j.core.model.OslcConstants"%>
<%@page import="org.eclipse.lyo.oslc4j.core.OSLC4JUtils"%>
<%@page import="org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition"%>
<%@page import="org.eclipse.lyo.oslc4j.core.annotation.OslcName"%>
<%@page import="java.lang.reflect.Method"%>
<%@page import="java.net.URI"%>
<%@page import="java.util.Collection"%>
<%@page import="java.util.Date"%>
<%@page import="java.util.HashSet"%>
<%@page import="java.util.List"%>
<%@page import="java.util.Iterator"%>
<%@page import="java.util.Map"%>
<%@page import="javax.xml.namespace.QName"%>
<%@page import="jakarta.ws.rs.core.UriBuilder"%>

<%@page import="se.kth.md.it.bcm.resources.BugzillaChangeRequest"%>
<%@page import="se.kth.md.it.bcm.resources.BugzDomainConstants"%>
<%@page import="se.kth.md.it.bcm.resources.Person"%>
<%@page import="se.kth.md.it.bcm.bugzilla.BugzillaArchive"%>
<%@page import="se.kth.md.it.bcm.bugzilla.Bug"%>
<%@page import="se.kth.md.it.bcm.bugzilla.Comment"%>

<%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %>

<% 
  BugzillaChangeRequest aBugzillaChangeRequest = (BugzillaChangeRequest) request.getAttribute("aBugzillaChangeRequest");
  String catalogUrl = UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path("/catalog/singleton").build().toString();
  Method method = null;
%>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title><%= aBugzillaChangeRequest.toString() %></title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  <link href="<c:url value="/static/css/adaptor.css"/>" rel="stylesheet">

  <script src="<c:url value="/static/js/ui-preview-helper.js"/>"></script>
  <script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
      setupUiPreviewOnPopover(document.querySelectorAll("a.oslc-resource-link"));
    });
  </script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300;400;500;600&display=swap" rel="stylesheet">
  <style>
      body {
          font-family: 'Fira Sans', sans-serif;
          background-color: #f8f9fa;
      }
      .page-header {
          margin-bottom: 2rem;
      }
      .card {
          box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075);
          border: none;
          margin-bottom: 2rem;
      }
      .card-header {
          background-color: #fff;
          border-bottom: 1px solid #eee;
          font-weight: 600;
          cursor: pointer;
      }
      dt {
          color: #6c757d;
          font-weight: 500;
          font-size: 0.9rem;
      }
      .dl-horizontal dt {
          float: left;
          width: 160px;
          overflow: hidden;
          clear: left;
          text-align: right;
          text-overflow: ellipsis;
          white-space: nowrap;
      }
      .dl-horizontal dd {
          margin-left: 180px;
      }
      .card-header::before {
          content: "\25B6";
          display: inline-block;
          margin-right: 0.5rem;
          font-size: 0.75rem;
          transition: transform 0.2s ease-in-out;
      }
      .card-header[aria-expanded="true"]::before {
          transform: rotate(90deg);
      }
      .card-header[aria-expanded="false"]::before {
          transform: rotate(0deg);
      }
  </style>
</head>

<body>
<!-- Fixed navbar -->
  <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="<c:url value="/"/>"><%= application.getServletContextName() %></a>
      <ul class="navbar-nav me-auto">
        <li class="nav-item"><a class="nav-link" href="<c:url value="<%= catalogUrl %>"/>">Service Provider Catalog</a></li>
        <li class="nav-item"><a class="nav-link" href="<c:url value="/swagger-ui/index.jsp"/>">Swagger UI</a></li>
      </ul>
    </div>
  </nav>

<!-- Begin page content -->
<div class="container py-4">
    <div class="page-header">
        <h1 class="display-5 mb-4"><%= aBugzillaChangeRequest.toString() %></h1>
    </div>

    <!-- Details Group -->
    <div class="card">
        <div class="card-header" data-bs-toggle="collapse" href="#collapseDetails" role="button" aria-expanded="true" aria-controls="collapseDetails">Details</div>
        <div class="collapse show" id="collapseDetails">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getIdentifier"); %>
                        <dt class="col-sm-6 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-6">
                        <% if (aBugzillaChangeRequest.getIdentifier() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.getIdentifier().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-8">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getTitle"); %>
                        <dt class="col-sm-3 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-9">
                        <% if (aBugzillaChangeRequest.getTitle() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.getTitle().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-4">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getStatus"); %>
                        <dt class="col-sm-6 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-6">
                        <% 
                        if (aBugzillaChangeRequest.getStatus() == null) { 
                            out.write("<em>null</em>"); 
                        } else { 
                            String status = aBugzillaChangeRequest.getStatus().toString();
                            String badgeClass = "bg-secondary";
                            if (status.equalsIgnoreCase("NEW") || status.equalsIgnoreCase("UNCONFIRMED")) {
                                badgeClass = "bg-primary";
                                if (aBugzillaChangeRequest.getSubject().contains("Status: Abandoned")) {
                                    badgeClass = "bg-warning text-dark";
                                }
                            }
                            else if (status.equalsIgnoreCase("RESOLVED") || status.equalsIgnoreCase("VERIFIED")) badgeClass = "bg-success";
                            else if (status.equalsIgnoreCase("CLOSED")) badgeClass = "bg-dark";
                            else if (status.equalsIgnoreCase("IN_PROGRESS") || status.equalsIgnoreCase("ASSIGNED")) badgeClass = "bg-info text-dark";
                            
                            out.write("<span class=\"badge rounded-pill " + badgeClass + "\">" + status + "</span>"); 
                        } 
                        %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-8">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getShortTitle"); %>
                        <dt class="col-sm-3 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-9">
                        <% if (aBugzillaChangeRequest.getShortTitle() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.getShortTitle().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-12">
                     <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getDescription"); %>
                        <dt class="col-sm-2 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-10">
                        <% if (aBugzillaChangeRequest.getDescription() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.getDescription().toString()); } %>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
        </div>
    </div>

    <!-- Comments Section -->
    <%
    Bug bug = BugzillaArchive.getInstance().getBug(Integer.parseInt(aBugzillaChangeRequest.getIdentifier()));
    if (bug != null && bug.getComments() != null && !bug.getComments().isEmpty()) {
        // Filter out the first comment (description) and private comments for the comments section
        int commentCount = 0;
        for (Comment comment : bug.getComments()) {
            if (comment.getCommentCount() > 0 && !comment.isPrivate()) {
                commentCount++;
            }
        }
        
        if (commentCount > 0) {
    %>
    <div class="card">
        <div class="card-header" data-bs-toggle="collapse" href="#collapseComments" role="button" aria-expanded="true" aria-controls="collapseComments">Comments (<%= commentCount %>)</div>
        <div class="collapse show" id="collapseComments">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <%
                    for (Comment comment : bug.getComments()) {
                        if (comment.getCommentCount() > 0 && !comment.isPrivate()) {
                    %>
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-9">
                                    <p class="card-text"><%= comment.getThetext() != null ? comment.getThetext() : "" %></p>
                                </div>
                                <div class="col-md-3 text-end">
                                    <small class="text-muted">
                                    <% if (comment.getWhoName() != null) { %>
                                        <%= comment.getWhoName() %>
                                    <% } else if (comment.getWho() != null) { %>
                                        <%= comment.getWho() %>
                                    <% } %>
                                    <br/>
                                    <% if (comment.getBugWhen() != null) { %>
                                        <%= comment.getBugWhen() %>
                                    <% } %>
                                    </small>
                                </div>
                            </div>
                        </div>
                    </div>
                    <%
                        }
                    }
                    %>
                </div>
            </div>
        </div>
        </div>
    </div>
    <%
        }
    }
    %>
    
    <!-- People Group -->
    <div class="card">
        <div class="card-header" data-bs-toggle="collapse" href="#collapsePeople" role="button" aria-expanded="true" aria-controls="collapsePeople">People</div>
        <div class="collapse show" id="collapsePeople">
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getCreator"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% 
                        Iterator<Person> creatorItr = aBugzillaChangeRequest.getCreator().iterator();
                        while(creatorItr.hasNext()) {
                            Person next = creatorItr.next();
                            request.setAttribute("aPerson", next); 
                        %>
                            <jsp:include page="/se/kth/md/it/bcm/persontohtml.jsp"><jsp:param name="asLocalResource" value="true"/></jsp:include>
                        <% 
                            request.removeAttribute("aPerson");
                            if (creatorItr.hasNext()) { out.write(", "); }
                        } 
                        %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getCreated"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.getCreated() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.getCreated().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getContributor"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% 
                        Iterator<Person> contributorItr = aBugzillaChangeRequest.getContributor().iterator();
                        while(contributorItr.hasNext()) {
                            Person next = contributorItr.next();
                            request.setAttribute("aPerson", next); 
                        %>
                            <jsp:include page="/se/kth/md/it/bcm/persontohtml.jsp"><jsp:param name="asLocalResource" value="true"/></jsp:include>
                        <% 
                            request.removeAttribute("aPerson");
                            if (contributorItr.hasNext()) { out.write(", "); }
                        } 
                        %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getModified"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.getModified() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.getModified().toString()); } %>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
        </div>
    </div>

    <!-- Categories Group -->
    <div class="card">
        <div class="card-header" data-bs-toggle="collapse" href="#collapseCategories" role="button" aria-expanded="true" aria-controls="collapseCategories">Categories</div>
        <div class="collapse show" id="collapseCategories">
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getProduct"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.getProduct() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.getProduct().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getComponent"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.getComponent() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.getComponent().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getVersion"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.getVersion() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.getVersion().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getPlatform"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.getPlatform() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.getPlatform().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getOperatingSystem"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.getOperatingSystem() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.getOperatingSystem().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getPriority"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.getPriority() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.getPriority().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getDctermsType"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <ul>
                        <% for(Object next : aBugzillaChangeRequest.getDctermsType()) { %>
                            <li><jsp:include page="/se/kth/md/it/bcm/typetohtml.jsp"><jsp:param name="asLocalResource" value="true"/></jsp:include></li>
                        <% } %>
                        </ul>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getSubject"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% 
                        for(String next : aBugzillaChangeRequest.getSubject()) { 
                            String pillClass = "bg-secondary";
                            if ("Status: Abandoned".equals(next)) pillClass = "bg-danger";
                            out.write("<span class=\"badge rounded-pill " + pillClass + " me-1\">" + next + "</span>"); 
                        } 
                        %>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
        </div>
    </div>

    <!-- Tracking Group -->
    <div class="card">
        <div class="card-header" data-bs-toggle="collapse" href="#collapseTracking" role="button" aria-expanded="true" aria-controls="collapseTracking">Tracking</div>
        <div class="collapse show" id="collapseTracking">
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getCloseDate"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.getCloseDate() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.getCloseDate().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("isFixed"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.isFixed() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.isFixed().toString()); } %>
                        </dd>
                    </dl>
                </div>
                 <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("isInprogress"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.isInprogress() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.isInprogress().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("isClosed"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.isClosed() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.isClosed().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("isApproved"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.isApproved() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.isApproved().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("isReviewed"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.isReviewed() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.isReviewed().toString()); } %>
                        </dd>
                    </dl>
                </div>
                 <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("isVerified"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.isVerified() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.isVerified().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getDiscussedBy"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if ((aBugzillaChangeRequest.getDiscussedBy() == null) || (aBugzillaChangeRequest.getDiscussedBy().getValue() == null)) { out.write("<em>null</em>"); } else { out.write("<a href=\"" + aBugzillaChangeRequest.getDiscussedBy().getValue().toString() + "\" class=\"oslc-resource-link\">"); out.write(aBugzillaChangeRequest.getDiscussedBy().getValue().toString()); out.write("</a>"); } %>
                        </dd>
                    </dl>
                </div>

                <!-- Links Section in Tracking -->
                <% 
                // Helper to render links
                String[] linkMethods = {
                    "getAffectedByDefect", "getAffectsPlanItem", "getAffectsRequirement", 
                    "getAffectsTestResult", "getBlocksTestExecutionRecord", 
                    "getImplementsRequirement", "getRelatedChangeRequest", 
                    "getRelatedTestCase", "getRelatedTestExecutionRecord", 
                    "getRelatedTestPlan", "getRelatedTestScript", 
                    "getTestedByTestCase", "getTracksChangeSet", "getTracksRequirement"
                };
                
                for(String methodName : linkMethods) {
                    method = BugzillaChangeRequest.class.getMethod(methodName);
                    // Dynamically invoke to get Collection<Link>
                    Collection<Link> links = (Collection<Link>) method.invoke(aBugzillaChangeRequest);
                %>
                <div class="col-md-6">
                    <dl class="row">
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <ul>
                        <% 
                        for(Link next : links) {
                            if (next.getValue() == null) {
                                out.write("<li>" + "<em>null</em>" + "</li>");
                            }
                            else {
                                out.write("<li>" + "<a href=\"" + next.getValue().toString() + "\" class=\"oslc-resource-link\">" + next.getValue().toString() + "</a>" + "</li>");
                            }
                        }
                        %> 
                        </ul>
                        </dd>
                    </dl>
                </div>
                <% } %>
            </div>
        </div>
        </div>
    </div>

    <!-- OSLC Metadata Group -->
    <div class="card">
        <div class="card-header collapsed" data-bs-toggle="collapse" href="#collapseOslcMetadata" role="button" aria-expanded="false" aria-controls="collapseOslcMetadata">OSLC Metadata</div>
        <div class="collapse" id="collapseOslcMetadata">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                     <dl class="row mb-1">
                        <dt class="col-sm-2 text-end">Resource URI</dt>
                        <dd class="col-sm-10">
                        <jsp:include page="/se/kth/md/it/bcm/bugzillachangerequesttohtml.jsp"></jsp:include>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-12">
                    <dl class="row mb-1">
                         <dt class="col-sm-2 text-end">Shape</dt>
                         <dd class="col-sm-10">
                            <% 
                            URI shapeUri = UriBuilder.fromUri(OSLC4JUtils.getServletURI()).path(OslcConstants.PATH_RESOURCE_SHAPES).path(BugzDomainConstants.BUGZILLACHANGEREQUEST_PATH).build();
                            %>
                            <a href="<%=shapeUri%>"><%=shapeUri%></a>
                         </dd>
                    </dl>
                </div>
                <div class="col-md-12">
                    <dl class="row mb-1">
                        <dt class="col-sm-2 text-end">rdf:type(s)</dt>
                        <dd class="col-sm-10">
                            <ul>
                            <%for (URI type : aBugzillaChangeRequest.getTypes()) {%> 
                            <li><a href="<%=type%>"><%=type%></a></li>
                            <%}%>
                            </ul>
                        </dd>
                    </dl>
                </div>
                 <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getServiceProvider"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if (aBugzillaChangeRequest.getServiceProvider() == null) { out.write("<em>null</em>"); } else { out.write(aBugzillaChangeRequest.getServiceProvider().toString()); } %>
                        </dd>
                    </dl>
                </div>
                <div class="col-md-6">
                    <dl class="row mb-1">
                        <% method = BugzillaChangeRequest.class.getMethod("getInstanceShape"); %>
                        <dt class="col-sm-4 text-end"><a href="<%=method.getAnnotation(OslcPropertyDefinition.class).value() %>"><%=method.getAnnotation(OslcName.class).value()%></a></dt>
                        <dd class="col-sm-8">
                        <% if ((aBugzillaChangeRequest.getInstanceShape() == null) || (aBugzillaChangeRequest.getInstanceShape().getValue() == null)) { out.write("<em>null</em>"); } else { out.write("<a href=\"" + aBugzillaChangeRequest.getInstanceShape().getValue().toString() + "\" class=\"oslc-resource-link\">"); out.write(aBugzillaChangeRequest.getInstanceShape().getValue().toString()); out.write("</a>"); } %>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>
        </div>
    </div>

    <!-- Extended Properties -->
    <% 
    Map<QName, Object> extendedProperties = aBugzillaChangeRequest.getExtendedProperties();
    if (!extendedProperties.isEmpty()) {
    %>
        <div class="card">
        <div class="card-header" data-bs-toggle="collapse" href="#collapseExtendedProperties" role="button" aria-expanded="true" aria-controls="collapseExtendedProperties">Extended Properties</div>
        <div class="collapse show" id="collapseExtendedProperties">
        <div class="card-body">
        <div class="row">
        <% 
        for (Map.Entry<QName, Object> entry : extendedProperties.entrySet()) 
        {
            QName key = entry.getKey();
            Object value = entry.getValue();
        %>
        <div class="col-md-6">
        <dl class="row mb-1">
            <dt class="col-sm-4 text-end"><a href="<%=key.getNamespaceURI() + key.getLocalPart() %>"><%=key.getLocalPart()%></a></dt>
            <dd class="col-sm-8"><%= value.toString()%></dd>
        </dl>
        </div>
        <% 
        }
        %>
        </div>
        </div>
        </div>
    <% 
    }
    %>
</div>
  <footer class="footer">
    <div class="container">
      <p class="text-muted">
        OSLC Adaptor was generated using <a href="http://eclipse.org/lyo">Eclipse Lyo</a>.
      </p>
    </div>
  </footer>
</body>
</html>