name: Acceptance test (Lyo HEAD)
run-name: "acceptance@${{ github.ref_name }} (Lyo@${{ inputs.lyoBranch }}; comment: ${{ inputs.comment }})"

on:
  workflow_dispatch:
    inputs:
      lyoBranch:
        description: Lyo branch to test on
        required: true
        default: main
      lyoRepo:
        description: Lyo repository or fork
        required: true
        default: eclipse-lyo/lyo
      comment:
        description: Comment, e.g. PR number
        default: n/a

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.lyoRepo }}-${{ inputs.lyoBranch }}
  cancel-in-progress: false

jobs:
  build:
    name: Build against Lyo HEAD
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ${{ inputs.lyoRepo }}
          ref: ${{ inputs.lyoBranch }}
          path: lyo-trunk
          persist-credentials: false
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: main
          persist-credentials: false
      - name: Set up JDK 25 (Jetty image fallback)
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: temurin
          java-version: '25'
      - name: Maven build (Lyo)
        run: mvn -B --no-transfer-progress clean install --file lyo-trunk/pom.xml -DskipTests -Dmaven.javadoc.skip=true
      - name: Maven build (project)
        run: mvn -B --no-transfer-progress clean verify --file main/source/BugzillaLyoArchives/pom.xml
